services:
  - type: web
    name: sensor-monitoring-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      SECRET_KEY:
        generateValue: true
